# build the iamges
# create containers
# connect them on defined network
# start them in foreground in terminal

services:
  nginx:
    build:
      context: ./requirements/nginx
      dockerfile: Dockerfile
    image: nginx
    pull_policy: never
    container_name: nginx
    depends_on:
      - mariadb
    ports: 
      - "443:443"
    volumes:
      - wp-volume:/var/www/html
    networks:
      inception:
    restart: unless-stopped

  wordpress:
    build:
      context: ./requirements/wordpress
      dockerfile: Dockerfile
    image: wordpress
    pull_policy: never
    container_name: wordpress
    env_file: .env
    depends_on:
      - mariadb
    volumes:
      - wp-volume:/var/www/html
    networks:
      inception:
    restart: unless-stopped

  mariadb:
    build:
      context: ./requirements/mariadb
      dockerfile: Dockerfile
    image: mariadb
    pull_policy: never
    container_name: mariadb
    env_file: .env
    volumes:
      - db-volume:/var/lib/mysql
    networks:
      inception:
    restart: unless-stopped

volumes:
  wp-volume:
    driver_opts:
      o: bind
      type: none
      device: /home/paula/data/wordpress_volume
  db-volume:
    driver_opts:
      o: bind
      type: none
      device: /home/paula/data/mariadb_volume

networks:
  inception:
    driver: bridge
